import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import styles from './page.module.css';
import { cn } from '@/lib/utils';

const inter = Inter({ 
    subsets: ['latin'],  
    variable: "--font-sans",
 });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
        )}`}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
